package ca.bc.gov.jag.shuber.persistence.dao;

import ca.bc.gov.jag.shuber.persistence.model.Address;
import java.util.UUID;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * AddressDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table address.
 *
 * @author hbm2dao
 * @version 391
 * @see ca.bc.gov.jag.shuber.persistence.model.Address
 */
@Repository
public interface AddressDAO extends JpaRepository<Address, UUID> {
    // NOTE: add custom methods here

}
