package ca.bc.gov.jag.shuber.persistence.dao;

import java.util.List;
import java.util.UUID;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ca.bc.gov.jag.shuber.persistence.model.AssignmentStream;

/**
 * AssignmentStreamDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table assignment_stream.
 *
 * @author hbm2dao
 * @version 352
 * @see ca.bc.gov.jag.shuber.persistence.model.AssignmentStream
 */
@Repository
public interface AssignmentStreamDAO extends JpaRepository<AssignmentStream, UUID> {
    // NOTE: add custom methods here

	/**
	 * Get assignments by given courthouse.
	 * @param locationId courthouse id
	 * @return list of records
	 */
	@Query("SELECT a FROM AssignmentStream a WHERE a.courthouse.locationId = :locationId")
	List<AssignmentStream> getAssignmentStreamsByCourthouse(@Param("locationId") UUID locationId);
	
}
