package ca.bc.gov.jag.shuber.persistence.dao;

import java.util.List;
import java.util.UUID;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ca.bc.gov.jag.shuber.persistence.model.Assignment;

/**
 * AssignmentDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table assignment.
 *
 * @author hbm2dao
 * @version 391
 * @see ca.bc.gov.jag.shuber.persistence.model.Assignment
 */
@Repository
public interface AssignmentDAO extends JpaRepository<Assignment, UUID> {
    // NOTE: add custom methods here
	

	@Query("SELECT a FROM Assignment a WHERE a.courthouse.courthouseId = :courthouseId")
	List<Assignment> findByCourthouseId(@Param("courthouseId") UUID courthouseId);
	
}
