package ca.bc.gov.jag.shuber.persistence.dao;

import java.util.UUID;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import ca.bc.gov.jag.shuber.persistence.model.Courtroom;

/**
 * CourtroomDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table courtroom.
 *
 * @author hbm2dao
 * @version 391
 * @see ca.bc.gov.jag.shuber.persistence.model.Courtroom
 */
//@Repository
@RepositoryRestResource
public interface CourtroomDAO extends JpaRepository<Courtroom, UUID> {
    // NOTE: add custom methods here

}
