package ca.bc.gov.jag.shuber.persistence.dao;

import java.util.Optional;
import java.util.UUID;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ca.bc.gov.jag.shuber.persistence.model.Courthouse;

/**
 * CourthouseDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table courthouse.
 *
 * @author hbm2dao
 * @version 391
 * @see ca.bc.gov.jag.shuber.persistence.model.Courthouse
 */
@Repository
public interface CourthouseDAO extends JpaRepository<Courthouse, UUID> {
    // NOTE: add custom methods here

	/**
	 * Find by courthouse business key.
	 * @param courthouseCd business key
	 * @return record
	 */
	Optional<Courthouse> findByCourthouseCd(@Param("courthouseCd") String courthouseCd);
	
}
