package ca.bc.gov.jag.shuber.persistence.dao;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

import javax.validation.constraints.NotNull;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import ca.bc.gov.jag.shuber.persistence.model.Duty;

/**
 * DutyDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table duty.
 *
 * @author hbm2dao
 * @version 391
 * @see ca.bc.gov.jag.shuber.persistence.model.Duty
 */
//@Repository
@RepositoryRestResource
public interface DutyDAO extends JpaRepository<Duty, UUID> {
    // NOTE: add custom methods here

	/**
	 * Find Duties by a courthouse and date range.
	 * <pre>
	 * A.end >= B.start AND A.start <= B.end
	 * </pre>
	 * @param courthouseId
	 * @param startDtm
	 * @param endDtm
	 * 
	 * @see https://stackoverflow.com/questions/325933/determine-whether-two-date-ranges-overlap
	 * @return records
	 */
	@Query("SELECT d FROM Duty d WHERE d.endDtm >= :startDateTime AND d.startDtm <= :endDateTime AND d.assignment.courthouse.courthouseId = :courthouseId")
	List<Duty> getByCourthouseAndDay(
		@NotNull @Param("courthouseId") UUID courthouseId,
		@NotNull @Param("startDateTime") LocalDateTime startDtm,
		@NotNull @Param("endDateTime") LocalDateTime endDtm);
	
}
