package ca.bc.gov.jag.shuber.persistence.dao;

import java.util.List;
import java.util.UUID;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import ca.bc.gov.jag.shuber.persistence.model.DutyRecurrence;

/**
 * DutyRecurrenceDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table duty_recurrence.
 *
 * @author hbm2dao
 * @version 391
 * @see ca.bc.gov.jag.shuber.persistence.model.DutyRecurrence
 */
@Repository
public interface DutyRecurrenceDAO extends JpaRepository<DutyRecurrence, UUID> {
    // NOTE: add custom methods here

	@Query("SELECT r FROM DutyRecurrence r WHERE r.assignment.courthouse.courthouseId = :courthouseId")
	List<DutyRecurrence> getDutyRecurrences(UUID courthouseId);

}
