package ca.bc.gov.jag.shuber.persistence.dao;

import java.util.UUID;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import ca.bc.gov.jag.shuber.persistence.model.Duty;
import ca.bc.gov.jag.shuber.persistence.model.projection.DutyWithDetail;

/**
 * DutyDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table duty.
 *
 * @author hbm2dao
 * @version 391
 * @see ca.bc.gov.jag.shuber.persistence.model.Duty
 */
@Repository
public interface DutyDAO extends JpaRepository<Duty, UUID> {
    // NOTE: add custom methods here

	@Query("SELECT d FROM Duty d WHERE d.dutyId = :dutyId")
	DutyWithDetail findDutyWithDetail(UUID dutyId);
	
}
