package ca.bc.gov.jag.shuber.persistence.dao;

import ca.bc.gov.jag.shuber.persistence.model.JailRoleCode;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * JailRoleCodeDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table jail_role_code.
 *
 * @author hbm2dao
 * @version 391
 * @see ca.bc.gov.jag.shuber.persistence.model.JailRoleCode
 */
@Repository
public interface JailRoleCodeDAO extends JpaRepository<JailRoleCode, String> {
    // NOTE: add custom methods here

}
