package ca.bc.gov.jag.shuber.persistence.dao;

import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import ca.bc.gov.jag.shuber.persistence.model.JailRoleCode;

/**
 * JailRoleCodeDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table jail_role_code.
 *
 * @author hbm2dao
 * @version 391
 * @see ca.bc.gov.jag.shuber.persistence.model.JailRoleCode
 */
//@Repository
@RepositoryRestResource
public interface JailRoleCodeDAO extends JpaRepository<JailRoleCode, String> {
    // NOTE: add custom methods here

	/**
	 * Find a jail role code.
	 * @param jailRoleCode jail role code
	 * @return record
	 */
	Optional<JailRoleCode> findByJailRoleCode(@Param("jailRoleCode") String jailRoleCode);
	
}
