package ca.bc.gov.jag.shuber.persistence.dao;

import ca.bc.gov.jag.shuber.persistence.model.Location;
import java.util.UUID;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * LocationDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table location.
 *
 * @author hbm2dao
 * @version 352
 * @see ca.bc.gov.jag.shuber.persistence.model.Location
 */
@Repository
public interface LocationDAO extends JpaRepository<Location, UUID> {
    // NOTE: add custom methods here

}
