package ca.bc.gov.jag.shuber.persistence.dao;

import ca.bc.gov.jag.shuber.persistence.model.LocationCode;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * LocationCodeDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table location_code.
 *
 * @author hbm2dao
 * @version 352
 * @see ca.bc.gov.jag.shuber.persistence.model.LocationCode
 */
@Repository
public interface LocationCodeDAO extends JpaRepository<LocationCode, String> {
    // NOTE: add custom methods here

}
