package ca.bc.gov.jag.shuber.persistence.dao;

import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import ca.bc.gov.jag.shuber.persistence.model.OtherAssignCode;

/**
 * OtherAssignCodeDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table other_assign_code.
 *
 * @author hbm2dao
 * @version 391
 * @see ca.bc.gov.jag.shuber.persistence.model.OtherAssignCode
 */
//@Repository
@RepositoryRestResource
public interface OtherAssignCodeDAO extends JpaRepository<OtherAssignCode, String> {
    // NOTE: add custom methods here

	/**
	 * Find an other assign code.
	 * @param otherAssignCode otherAssignCode
	 * @return record
	 */
	Optional<OtherAssignCode> findByOtherAssignCode(@Param("otherAssignCode") String otherAssignCode);
	
}
