package ca.bc.gov.jag.shuber.persistence.dao;

import ca.bc.gov.jag.shuber.persistence.model.Run;
import java.util.UUID;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * RunDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table run.
 *
 * @author hbm2dao
 * @version 391
 * @see ca.bc.gov.jag.shuber.persistence.model.Run
 */
@Repository
public interface RunDAO extends JpaRepository<Run, UUID> {
    // NOTE: add custom methods here

}
