package ca.bc.gov.jag.shuber.persistence.dao;

import ca.bc.gov.jag.shuber.persistence.model.SheriffDuty;
import java.util.UUID;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * SheriffDutyDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table sheriff_duty.
 *
 * @author hbm2dao
 * @version 391
 * @see ca.bc.gov.jag.shuber.persistence.model.SheriffDuty
 */
@Repository
public interface SheriffDutyDAO extends JpaRepository<SheriffDuty, UUID> {
    // NOTE: add custom methods here

}
