package ca.bc.gov.jag.shuber.persistence.dao;

import java.util.List;
import java.util.UUID;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import ca.bc.gov.jag.shuber.persistence.model.Sheriff;

/**
 * SheriffDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table sheriff.
 *
 * @author hbm2dao
 * @version 391
 * @see ca.bc.gov.jag.shuber.persistence.model.Sheriff
 */
@Repository
public interface SheriffDAO extends JpaRepository<Sheriff, UUID> {
    // NOTE: add custom methods here

	/**
	 * Find a sheriff by their badge number.
	 * @param badgeNo badge number
	 * @return record
	 */
	Sheriff findByBadgeNo(@Param("badgeNo") String badgeNo);
	
	/**
	 * Find by user id. 
	 * @param userid user id
	 * @return record
	 */
	Sheriff findByUserid(@Param("userid") String userid);
	
	/**
	 * Find sheriffs for given courthouse.
	 * @param courthouseId courthouse
	 * @return records
	 */
	@Query("SELECT s FROM Sheriff s WHERE s.courthouse.courthouseId = :courthouseId")
	List<Sheriff> getSheriffsByCourthouse(@Param("courthouseId") UUID courthouseId);
	
}
