package ca.bc.gov.jag.shuber.persistence.dao;

import java.util.UUID;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import ca.bc.gov.jag.shuber.persistence.model.Shift;

/**
 * ShiftDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table shift.
 *
 * @author hbm2dao
 * @version 400
 * @see ca.bc.gov.jag.shuber.persistence.model.Shift
 */
//@Repository
@RepositoryRestResource
public interface ShiftDAO extends JpaRepository<Shift, UUID> {
    // NOTE: add custom methods here

}
