package ca.bc.gov.jag.shuber.persistence.dao;

import ca.bc.gov.jag.shuber.persistence.model.Assignment;
import java.util.UUID;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * AssignmentDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table assignment.
 *
 * @author hbm2dao
 * @version 346
 * @see ca.bc.gov.jag.shuber.persistence.model.Assignment
 */
@Repository
public interface AssignmentDAO extends JpaRepository<Assignment, UUID> {
    // NOTE: add custom methods here

}
