package ca.bc.gov.jag.shuber.persistence.dao;

import ca.bc.gov.jag.shuber.persistence.model.AssignmentTemplate;
import java.util.UUID;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * AssignmentTemplateDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table assignment_template.
 *
 * @author hbm2dao
 * @version 346
 * @see ca.bc.gov.jag.shuber.persistence.model.AssignmentTemplate
 */
@Repository
public interface AssignmentTemplateDAO extends JpaRepository<AssignmentTemplate, UUID> {
    // NOTE: add custom methods here

}
