package ca.bc.gov.jag.shuber.persistence.dao;

import ca.bc.gov.jag.shuber.persistence.model.AssignmentStream;
import java.util.UUID;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * AssignmentStreamDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table assignment_stream.
 *
 * @author hbm2dao
 * @version 346
 * @see ca.bc.gov.jag.shuber.persistence.model.AssignmentStream
 */
@Repository
public interface AssignmentStreamDAO extends JpaRepository<AssignmentStream, UUID> {
    // NOTE: add custom methods here

}
