package ca.bc.gov.jag.shuber.persistence.dao;

import ca.bc.gov.jag.shuber.persistence.model.Courthouse;
import java.util.UUID;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * CourthouseDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table courthouse.
 *
 * @author hbm2dao
 * @version 352
 * @see ca.bc.gov.jag.shuber.persistence.model.Courthouse
 */
@Repository
public interface CourthouseDAO extends JpaRepository<Courthouse, UUID> {
    // NOTE: add custom methods here

}
