package ca.bc.gov.jag.shuber.persistence.dao;

import ca.bc.gov.jag.shuber.persistence.model.Recurrence;
import java.util.UUID;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * RecurrenceDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table recurrence.
 *
 * @author hbm2dao
 * @version 346
 * @see ca.bc.gov.jag.shuber.persistence.model.Recurrence
 */
@Repository
public interface RecurrenceDAO extends JpaRepository<Recurrence, UUID> {
    // NOTE: add custom methods here

}
