package ca.bc.gov.jag.shuber.persistence.dao;

import ca.bc.gov.jag.shuber.persistence.model.Region;
import java.util.UUID;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * RegionDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table region.
 *
 * @author hbm2dao
 * @version 352
 * @see ca.bc.gov.jag.shuber.persistence.model.Region
 */
@Repository
public interface RegionDAO extends JpaRepository<Region, UUID> {
    // NOTE: add custom methods here

}
