package ca.bc.gov.jag.shuber.persistence.dao;

import ca.bc.gov.jag.shuber.persistence.model.Sheriff;
import java.util.UUID;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * SheriffDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table sheriff.
 *
 * @author hbm2dao
 * @version 352
 * @see ca.bc.gov.jag.shuber.persistence.model.Sheriff
 */
@Repository
public interface SheriffDAO extends JpaRepository<Sheriff, UUID> {
    // NOTE: add custom methods here

	/**
	 * 
	 * @param badgeNo
	 * @return
	 */
	Sheriff findByBadgeNo(String badgeNo);
}
