package ca.bc.gov.jag.shuber.persistence.dao;

import java.util.Date;
import java.util.List;
import java.util.UUID;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import ca.bc.gov.jag.shuber.persistence.model.Shift;

/**
 * ShiftDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table shift.
 *
 * @author hbm2dao
 * @version 346
 * @see ca.bc.gov.jag.shuber.persistence.model.Shift
 */
@Repository
public interface ShiftDAO extends JpaRepository<Shift, UUID> {
    // NOTE: add custom methods here

	/**
	 * 
	 * @param orgUnitId
	 * @param shiftDate
	 * @param endDate
	 * @return
	 */
	//NOTE: use @Query("") to execute a custom one
	List<Shift> getShifts(UUID orgUnitId, Date shiftDate, Date endDate);
}
