package ca.bc.gov.jag.shuber.persistence.dao;

import ca.bc.gov.jag.shuber.persistence.model.WorkSectionCode;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * WorkSectionCodeDAO generated by Hibernate Tools hbm2dao.
 *
 * <p>Domain data access object for database table work_section_code.
 *
 * @author hbm2dao
 * @version 346
 * @see ca.bc.gov.jag.shuber.persistence.model.WorkSectionCode
 */
@Repository
public interface WorkSectionCodeDAO extends JpaRepository<WorkSectionCode, String> {
    // NOTE: add custom methods here

}
