package ca.bc.gov.jag.shuber.persistence.model;

import ca.bc.gov.jag.shuber.persistence.AbstractAuditableVersionable;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import org.hibernate.annotations.GenericGenerator;

/**
 * Duty generated by Hibernate Tools hbm2java.
 *
 * <p>Domain model for database table duty.
 *
 * @author hbm2java
 * @version 391
 */
@Entity
@Table(name = "duty"
    // ,schema="shersched"
)
public class Duty extends AbstractAuditableVersionable implements Serializable {

    /** UID. */
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Column(name = "duty_id", nullable = false, updatable = false)
    private UUID dutyId;

    @NotNull
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assignment_id", nullable = false)
    private Assignment assignment;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "start_dtm", length = 35)
    private Date startDtm;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "end_dtm", length = 35)
    private Date endDtm;

    @NotNull
    @Column(name = "sheriffs_required", nullable = false, precision = 2, scale = 0)
    private byte sheriffsRequired;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "duty")
    private List<SheriffDuty> sheriffDuties = new ArrayList<SheriffDuty>(0);
    
    /** No args constructor. */
    public Duty() {}

    /** Required args constructor. */
    public Duty(
            UUID dutyId,
            Assignment assignment,
            byte sheriffsRequired,
            String createdBy,
            String updatedBy,
            Date createdDtm,
            Date updatedDtm,
            long revisionCount) {
        this.dutyId = dutyId;
        this.assignment = assignment;
        this.sheriffsRequired = sheriffsRequired;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
    }

    /** All args constructor. */
    public Duty(
            UUID dutyId,
            Assignment assignment,
            Date startDtm,
            Date endDtm,
            byte sheriffsRequired,
            String createdBy,
            String updatedBy,
            Date createdDtm,
            Date updatedDtm,
            long revisionCount,
            List<SheriffDuty> sheriffDuties) {
        this.dutyId = dutyId;
        this.assignment = assignment;
        this.startDtm = startDtm;
        this.endDtm = endDtm;
        this.sheriffsRequired = sheriffsRequired;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
        this.sheriffDuties = sheriffDuties;
    }

    public UUID getDutyId() {
        return this.dutyId;
    }

    public void setDutyId(UUID dutyId) {
        this.dutyId = dutyId;
    }

    public Assignment getAssignment() {
        return this.assignment;
    }

    public void setAssignment(Assignment assignment) {
        this.assignment = assignment;
    }

    public Date getStartDtm() {
        return this.startDtm;
    }

    public void setStartDtm(Date startDtm) {
        this.startDtm = startDtm;
    }

    public Date getEndDtm() {
        return this.endDtm;
    }

    public void setEndDtm(Date endDtm) {
        this.endDtm = endDtm;
    }

    public byte getSheriffsRequired() {
        return this.sheriffsRequired;
    }

    public void setSheriffsRequired(byte sheriffsRequired) {
        this.sheriffsRequired = sheriffsRequired;
    }

    public List<SheriffDuty> getSheriffDuties() {
        return this.sheriffDuties;
    }

    public void setSheriffDuties(List<SheriffDuty> sheriffDuties) {
        this.sheriffDuties = sheriffDuties;
    }
}
