package ca.bc.gov.jag.shuber.persistence.model;

import java.io.Serializable;
import java.time.Instant;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.GenericGenerator;

import com.fasterxml.jackson.annotation.JsonProperty;

import ca.bc.gov.jag.shuber.persistence.AbstractAuditableVersionable;

/**
 * Duty generated by Hibernate Tools hbm2java.
 *
 * <p>Domain model for database table duty.
 *
 * @author hbm2java
 * @version 391
 */
@Entity
@Table(name = "duty"
    // ,schema="shersched"
)
public class Duty extends AbstractAuditableVersionable implements Serializable {

	/** UID. */
    private static final long serialVersionUID = 1L;
	
	@Id
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Column(name = "duty_id", nullable = false, updatable = false)
    private UUID dutyId;

    @NotNull
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assignment_id", nullable = false)
    private Assignment assignment;

    @JsonProperty("startDateTime")
    @NotNull
    @Column(name = "start_dtm", nullable = false, length = 35)
    private LocalDateTime startDtm;

    @JsonProperty("endDateTime")
    @NotNull
    @Column(name = "end_dtm", nullable = false, length = 35)
    private LocalDateTime endDtm;

    @NotNull
    @Column(name = "sheriffs_required", nullable = false, precision = 2, scale = 0)
    private byte sheriffsRequired;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "duty", cascade = CascadeType.ALL)
    private List<SheriffDuty> sheriffDuties = new ArrayList<SheriffDuty>(0);
    
    /** No args constructor. */
    public Duty() {}

    /** Required args constructor. */
    public Duty(
            UUID dutyId,
            Assignment assignment,
            LocalDateTime startDtm,
            LocalDateTime endDtm,
            byte sheriffsRequired,
            String createdBy,
            String updatedBy,
            Instant createdDtm,
            Instant updatedDtm,
            long revisionCount) {
        this.dutyId = dutyId;
        this.assignment = assignment;
        this.startDtm = startDtm;
        this.endDtm = endDtm;
        this.sheriffsRequired = sheriffsRequired;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
    }

    /** All args constructor. */
    public Duty(
            UUID dutyId,
            Assignment assignment,
            LocalDateTime startDtm,
            LocalDateTime endDtm,
            byte sheriffsRequired,
            String createdBy,
            String updatedBy,
            Instant createdDtm,
            Instant updatedDtm,
            long revisionCount,
            List<SheriffDuty> sheriffDuties) {
        this.dutyId = dutyId;
        this.assignment = assignment;
        this.startDtm = startDtm;
        this.endDtm = endDtm;
        this.sheriffsRequired = sheriffsRequired;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
        this.sheriffDuties = sheriffDuties;
    }

    public UUID getDutyId() {
        return this.dutyId;
    }

    public void setDutyId(UUID dutyId) {
        this.dutyId = dutyId;
    }

    public Assignment getAssignment() {
        return this.assignment;
    }

    public void setAssignment(Assignment assignment) {
        this.assignment = assignment;
    }

    public LocalDateTime getStartDtm() {
        return this.startDtm;
    }

    public void setStartDtm(LocalDateTime startDtm) {
        this.startDtm = startDtm;
    }

    public LocalDateTime getEndDtm() {
        return this.endDtm;
    }

    public void setEndDtm(LocalDateTime endDtm) {
        this.endDtm = endDtm;
    }

    public byte getSheriffsRequired() {
        return this.sheriffsRequired;
    }

    public void setSheriffsRequired(byte sheriffsRequired) {
        this.sheriffsRequired = sheriffsRequired;
    }

    public List<SheriffDuty> getSheriffDuties() {
        return this.sheriffDuties;
    }

    public void setSheriffDuties(List<SheriffDuty> sheriffDuties) {
        this.sheriffDuties = sheriffDuties;
    }
    
    @Transient
	@Override
	public String getIdPath() {
		return "/duties/" + dutyId;
	}
}
