package ca.bc.gov.jag.shuber.persistence.model;

import java.io.Serializable;
import java.time.Instant;
import java.time.LocalTime;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.GenericGenerator;

import ca.bc.gov.jag.shuber.persistence.AbstractAuditableVersionable;

/**
 * DutyRecurrence generated by Hibernate Tools hbm2java.
 *
 * <p>Domain model for database table duty_recurrence.
 *
 * @author hbm2java
 * @version 391
 */
@Entity
@Table(name = "duty_recurrence"
    // ,schema="shersched"
)
public class DutyRecurrence extends AbstractAuditableVersionable implements Serializable {

    /** UID. */
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Column(name = "duty_recurrence_id", nullable = false, updatable = false)
    private UUID dutyRecurrenceId;

    @NotNull
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assignment_id", nullable = false)
    private Assignment assignment;
    
    @NotNull
    @Column(name = "start_time", nullable = false, length = 15)
    private LocalTime startTime;

    @NotNull
    @Column(name = "end_time", nullable = false, length = 15)
    private LocalTime endTime;

    @NotNull
    @Column(name = "days_bitmap", nullable = false, precision = 10, scale = 0)
    private long daysBitmap;

    @NotNull
    @Column(name = "sheriffs_required", nullable = false, precision = 2, scale = 0)
    private byte sheriffsRequired;
    /** No args constructor. */
    public DutyRecurrence() {}

    /** All args constructor. */
    public DutyRecurrence(
            UUID dutyRecurrenceId,
            Assignment assignment,
            LocalTime startTime,
            LocalTime endTime,
            long daysBitmap,
            byte sheriffsRequired,
            String createdBy,
            String updatedBy,
            Instant createdDtm,
            Instant updatedDtm,
            long revisionCount) {
        this.dutyRecurrenceId = dutyRecurrenceId;
        this.assignment = assignment;
        this.startTime = startTime;
        this.endTime = endTime;    
        this.daysBitmap = daysBitmap;
        this.sheriffsRequired = sheriffsRequired;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
    }

    public UUID getDutyRecurrenceId() {
        return this.dutyRecurrenceId;
    }

    public void setDutyRecurrenceId(UUID dutyRecurrenceId) {
        this.dutyRecurrenceId = dutyRecurrenceId;
    }

    public Assignment getAssignment() {
        return this.assignment;
    }

    public void setAssignment(Assignment assignment) {
        this.assignment = assignment;
    }
    
	public LocalTime getStartTime() {
		return this.startTime;
	}

	public void setStartTime(LocalTime startTime) {
		this.startTime = startTime;
	}

	public LocalTime getEndTime() {
		return this.endTime;
	}

	public void setEndTime(LocalTime endTime) {
		this.endTime = endTime;
	}

    public long getDaysBitmap() {
        return this.daysBitmap;
    }

    public void setDaysBitmap(long daysBitmap) {
        this.daysBitmap = daysBitmap;
    }

    public byte getSheriffsRequired() {
        return this.sheriffsRequired;
    }

    public void setSheriffsRequired(byte sheriffsRequired) {
        this.sheriffsRequired = sheriffsRequired;
    }
    
    @Transient
	@Override
	public String getIdPath() {
		return "/dutyRecurrences/" + dutyRecurrenceId;
	}
}
