package ca.bc.gov.jag.shuber.persistence.model;

import java.io.Serializable;
import java.time.Instant;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;

import ca.bc.gov.jag.shuber.persistence.AbstractTypeCode;

/**
 * JailRoleCode generated by Hibernate Tools hbm2java.
 *
 * <p>Domain model for database table jail_role_code.
 *
 * @author hbm2java
 * @version 391
 */
@Entity
@Table(name = "jail_role_code"
    // ,schema="shersched"
)
public class JailRoleCode extends AbstractTypeCode implements Serializable {
	public enum JAIL_ROLE_CODE {
		SERGEANT,
		DEPUTYSERGEANT,
		CONTROL,
		PRETRIAL,
		;
	}
	
    /** UID. */
    private static final long serialVersionUID = 1L;

    @Id
    @Size(min = 1, max = 20)
    @Column(name = "jail_role_code", nullable = false, updatable = false, length = 20)
    private String jailRoleCode;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "jailRoleCode")
    private List<Assignment> assignments = new ArrayList<Assignment>(0);
    /** No args constructor. */
    public JailRoleCode() {}

    /** Required args constructor. */
    public JailRoleCode(
            String jailRoleCode,
            String description,
            LocalDate effectiveDate,
            String createdBy,
            String updatedBy,
            Instant createdDtm,
            Instant updatedDtm,
            long revisionCount) {
        this.jailRoleCode = jailRoleCode;
        this.description = description;
        this.effectiveDate = effectiveDate;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
    }

    /** All args constructor. */
    public JailRoleCode(
            String jailRoleCode,
            String description,
            LocalDate effectiveDate,
            LocalDate expiryDate,
            String createdBy,
            String updatedBy,
            Instant createdDtm,
            Instant updatedDtm,
            long revisionCount,
            List<Assignment> assignments) {
        this.jailRoleCode = jailRoleCode;
        this.description = description;
        this.effectiveDate = effectiveDate;
        this.expiryDate = expiryDate;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
        this.assignments = assignments;
    }

    public String getJailRoleCode() {
        return this.jailRoleCode;
    }

    public void setJailRoleCode(String jailRoleCode) {
        this.jailRoleCode = jailRoleCode;
    }

    public List<Assignment> getAssignments() {
        return this.assignments;
    }

    public void setAssignments(List<Assignment> assignments) {
        this.assignments = assignments;
    }
    
    //Added Methods
    @Transient
	@Override
	public String getTypeCode() {
		return jailRoleCode;
	} 
    
    @Transient
	@Override
	public String getIdPath() {
		return "/jailRoleCodes/" + jailRoleCode;
	}
}
