package ca.bc.gov.jag.shuber.persistence.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;

import ca.bc.gov.jag.shuber.persistence.AbstractTypeCode;

/**
 * LocationCode generated by Hibernate Tools hbm2java.
 *
 * <p>Domain model for database table location_code.
 *
 * @author hbm2java
 * @version 352
 */
@Entity
@Table(name = "location_code"
    // ,schema="shersched"
)
public class LocationCode extends AbstractTypeCode implements Serializable {

    /** UID. */
    private static final long serialVersionUID = 1L;

    @Id
    @Size(min = 1, max = 20)
    @Column(name = "location_code", nullable = false, updatable = false, length = 20)
    private String locationCode;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "locationCode")
    private List<Location> locations = new ArrayList<Location>(0);
    
    /** No args constructor. */
    public LocationCode() {}

    /** Required args constructor. */
    public LocationCode(
            String locationCode,
            String description,
            Date effectiveDate,
            String createdBy,
            String updatedBy,
            Date createdDtm,
            Date updatedDtm,
            long revisionCount) {
        this.locationCode = locationCode;
        this.description = description;
        this.effectiveDate = effectiveDate;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
    }

    /** All args constructor. */
    public LocationCode(
            String locationCode,
            String description,
            Date effectiveDate,
            Date expiryDate,
            String createdBy,
            String updatedBy,
            Date createdDtm,
            Date updatedDtm,
            long revisionCount,
            List<Location> locations) {
        this.locationCode = locationCode;
        this.description = description;
        this.effectiveDate = effectiveDate;
        this.expiryDate = expiryDate;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
        this.locations = locations;
    }

    public String getLocationCode() {
        return this.locationCode;
    }

    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }

    public List<Location> getLocations() {
        return this.locations;
    }

    public void setLocations(List<Location> locations) {
        this.locations = locations;
    }

    @Transient
	@Override
	public String getTypeCode() {
		return locationCode;
	}

}
