package ca.bc.gov.jag.shuber.persistence.model;

import java.io.Serializable;
import java.time.Instant;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;

import ca.bc.gov.jag.shuber.persistence.AbstractTypeCode;

/**
 * OtherAssignCode generated by Hibernate Tools hbm2java.
 *
 * <p>Domain model for database table other_assign_code.
 *
 * @author hbm2java
 * @version 391
 */
@Entity
@Table(name = "other_assign_code"
    // ,schema="shersched"
)
public class OtherAssignCode extends AbstractTypeCode implements Serializable {
	public enum OTHER_ASSIGN_CODE {
		GATE1,
		GATE2,
		JURYSELECT,
		JURYDELIB,
		DOCUMENTS,
		;
	}
	
    /** UID. */
    private static final long serialVersionUID = 1L;

    @Id
    @Size(min = 1, max = 20)
    @Column(name = "other_assign_code", nullable = false, updatable = false, length = 20)
    private String otherAssignCode;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "otherAssignCode")
    private List<Assignment> assignments = new ArrayList<Assignment>(0);
    
    /** No args constructor. */
    public OtherAssignCode() {}

    /** Required args constructor. */
    public OtherAssignCode(
            String otherAssignCode,
            String description,
            LocalDate effectiveDate,
            String createdBy,
            String updatedBy,
            Instant createdDtm,
            Instant updatedDtm,
            long revisionCount) {
        this.otherAssignCode = otherAssignCode;
        this.description = description;
        this.effectiveDate = effectiveDate;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
    }

    /** All args constructor. */
    public OtherAssignCode(
            String otherAssignCode,
            String description,
            LocalDate effectiveDate,
            LocalDate expiryDate,
            String createdBy,
            String updatedBy,
            Instant createdDtm,
            Instant updatedDtm,
            long revisionCount,
            List<Assignment> assignments) {
        this.otherAssignCode = otherAssignCode;
        this.description = description;
        this.effectiveDate = effectiveDate;
        this.expiryDate = expiryDate;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
        this.assignments = assignments;
    }

    public String getOtherAssignCode() {
        return this.otherAssignCode;
    }

    public void setOtherAssignCode(String otherAssignCode) {
        this.otherAssignCode = otherAssignCode;
    }

    public List<Assignment> getAssignments() {
        return this.assignments;
    }

    public void setAssignments(List<Assignment> assignments) {
        this.assignments = assignments;
    }
    
    //Added Methods
    @Transient
	@Override
	public String getTypeCode() {
		return otherAssignCode;
	} 
    
    @Transient
	@Override
	public String getIdPath() {
		return "/otherAssignCodes/" + otherAssignCode;
	}
}
