package ca.bc.gov.jag.shuber.persistence.model;

import ca.bc.gov.jag.shuber.persistence.AbstractTypeCode;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;

/**
 * SheriffRankCode generated by Hibernate Tools hbm2java.
 *
 * <p>Domain model for database table sheriff_rank_code.
 *
 * @author hbm2java
 * @version 391
 */
@Entity
@Table(name = "sheriff_rank_code"
    // ,schema="shersched"
)
public class SheriffRankCode extends AbstractTypeCode implements Serializable {

    /** UID. */
    private static final long serialVersionUID = 1L;

    @Id
    @Size(min = 1, max = 20)
    @Column(name = "sheriff_rank_code", nullable = false, updatable = false, length = 20)
    private String sheriffRankCode;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sheriffRankCode")
    private List<Sheriff> sheriffs = new ArrayList<Sheriff>(0);
    
    /** No args constructor. */
    public SheriffRankCode() {}

    /** Required args constructor. */
    public SheriffRankCode(
            String sheriffRankCode,
            String description,
            Date effectiveDate,
            String createdBy,
            String updatedBy,
            Date createdDtm,
            Date updatedDtm,
            long revisionCount) {
        this.sheriffRankCode = sheriffRankCode;
        this.description = description;
        this.effectiveDate = effectiveDate;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
    }

    /** All args constructor. */
    public SheriffRankCode(
            String sheriffRankCode,
            String description,
            Date effectiveDate,
            Date expiryDate,
            String createdBy,
            String updatedBy,
            Date createdDtm,
            Date updatedDtm,
            long revisionCount,
            List<Sheriff> sheriffs) {
        this.sheriffRankCode = sheriffRankCode;
        this.description = description;
        this.effectiveDate = effectiveDate;
        this.expiryDate = expiryDate;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
        this.sheriffs = sheriffs;
    }

    public String getSheriffRankCode() {
        return this.sheriffRankCode;
    }

    public void setSheriffRankCode(String sheriffRankCode) {
        this.sheriffRankCode = sheriffRankCode;
    }

    public List<Sheriff> getSheriffs() {
        return this.sheriffs;
    }

    public void setSheriffs(List<Sheriff> sheriffs) {
        this.sheriffs = sheriffs;
    }
    
    //Added Methods
    @Transient
	@Override
	public String getTypeCode() {
		return sheriffRankCode;
	} 
}
