package ca.bc.gov.jag.shuber.persistence.model;

import java.io.Serializable;
import java.time.Instant;
import java.time.LocalDateTime;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.GenericGenerator;

import com.fasterxml.jackson.annotation.JsonProperty;

import ca.bc.gov.jag.shuber.persistence.AbstractAuditableVersionable;
import ca.bc.gov.jag.shuber.persistence.DateTimeRange;

/**
 * Shift generated by Hibernate Tools hbm2java.
 *
 * <p>Domain model for database table shift.
 *
 * @author hbm2java
 * @version 406
 */
@Entity
@Table(name = "shift"
    // ,schema="shersched"
)
public class Shift extends AbstractAuditableVersionable implements DateTimeRange, Serializable {

    /** UID. */
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Column(name = "shift_id", nullable = false, updatable = false)
    private UUID shiftId;

    @NotNull
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "courthouse_id", nullable = false)
    private Courthouse courthouse;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sheriff_id")
    private Sheriff sheriff;

    @NotNull
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "work_section_code", nullable = false)
    private WorkSectionCode workSectionCode;

    @JsonProperty("startDateTime")
    @NotNull
    @Column(name = "start_dtm", nullable = false, length = 35)
    private LocalDateTime startDtm;

    @JsonProperty("endDateTime")
    @NotNull
    @Column(name = "end_dtm", nullable = false, length = 35)
    private LocalDateTime endDtm;
    
    /** No args constructor. */
    public Shift() {}

    /** Required args constructor. */
    public Shift(
            UUID shiftId,
            Courthouse courthouse,
            WorkSectionCode workSectionCode,
            LocalDateTime startDtm,
            LocalDateTime endDtm,
            String createdBy,
            String updatedBy,
            Instant createdDtm,
            Instant updatedDtm,
            long revisionCount) {
        this.shiftId = shiftId;
        this.courthouse = courthouse;
        this.workSectionCode = workSectionCode;
        this.startDtm = startDtm;
        this.endDtm = endDtm;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
    }

    /** All args constructor. */
    public Shift(
            UUID shiftId,
            Courthouse courthouse,
            Sheriff sheriff,
            WorkSectionCode workSectionCode,
            LocalDateTime startDtm,
            LocalDateTime endDtm,
            String createdBy,
            String updatedBy,
            Instant createdDtm,
            Instant updatedDtm,
            long revisionCount) {
        this.shiftId = shiftId;
        this.courthouse = courthouse;
        this.sheriff = sheriff;
        this.workSectionCode = workSectionCode;
        this.startDtm = startDtm;
        this.endDtm = endDtm;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
    }

    public UUID getShiftId() {
        return this.shiftId;
    }

    public void setShiftId(UUID shiftId) {
        this.shiftId = shiftId;
    }

    public Courthouse getCourthouse() {
        return this.courthouse;
    }

    public void setCourthouse(Courthouse courthouse) {
        this.courthouse = courthouse;
    }

    public Sheriff getSheriff() {
        return this.sheriff;
    }

    public void setSheriff(Sheriff sheriff) {
        this.sheriff = sheriff;
    }

    public WorkSectionCode getWorkSectionCode() {
        return this.workSectionCode;
    }

    public void setWorkSectionCode(WorkSectionCode workSectionCode) {
        this.workSectionCode = workSectionCode;
    }

    @Override
    public LocalDateTime getStartDtm() {
        return this.startDtm;
    }

    @Override
    public void setStartDtm(LocalDateTime startDtm) {
        this.startDtm = startDtm;
    }

    @Override
    public LocalDateTime getEndDtm() {
        return this.endDtm;
    }

    @Override
    public void setEndDtm(LocalDateTime endDtm) {
        this.endDtm = endDtm;
    }
    
    @Transient
	@Override
	public String getIdPath() {
		return "/shifts/" + shiftId;
	}
    
}
