-- set schema
SET search_path TO ${POSTGRES_SCHEMA};

-- ASSIGNMENT
INSERT INTO assignment (assignment_id,courthouse_id,courtroom_id,jail_role_code,other_assign_code,run_id,work_section_code,title,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),(SELECT c.courtroom_id FROM courtroom c WHERE c.courtroom_cd = 'VICTORIA101'),null,null,null,'COURTS','Title 1','test','test',now(),now(),0);
INSERT INTO assignment (assignment_id,courthouse_id,courtroom_id,jail_role_code,other_assign_code,run_id,work_section_code,title,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),(SELECT c.courtroom_id FROM courtroom c WHERE c.courtroom_cd = 'VICTORIA301'),null,null,null,'COURTS','Title 2','test','test',now(),now(),0);
INSERT INTO assignment (assignment_id,courthouse_id,courtroom_id,jail_role_code,other_assign_code,run_id,work_section_code,title,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),null,'SERGEANT',null,null,'JAIL','Jail 1','test','test',now(),now(),0);
INSERT INTO assignment (assignment_id,courthouse_id,courtroom_id,jail_role_code,other_assign_code,run_id,work_section_code,title,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),null,'DEPUTYSERGEANT',null,null,'JAIL','Jail 2','test','test',now(),now(),0);
INSERT INTO assignment (assignment_id,courthouse_id,courtroom_id,jail_role_code,other_assign_code,run_id,work_section_code,title,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),null,null,null,(SELECT r.run_id FROM run r WHERE r.courthouse_id = (SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201') AND r.title = 'Run 1'),'ESCORTS','Escort 1','test','test',now(),now(),0);
INSERT INTO assignment (assignment_id,courthouse_id,courtroom_id,jail_role_code,other_assign_code,run_id,work_section_code,title,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),null,null,null,(SELECT r.run_id FROM run r WHERE r.courthouse_id = (SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201') AND r.title = 'Run 2'),'ESCORTS','Escort 2','test','test',now(),now(),0);
INSERT INTO assignment (assignment_id,courthouse_id,courtroom_id,jail_role_code,other_assign_code,run_id,work_section_code,title,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),null,null,'GATE1',null,'OTHER','Other 1','test','test',now(),now(),0);
INSERT INTO assignment (assignment_id,courthouse_id,courtroom_id,jail_role_code,other_assign_code,run_id,work_section_code,title,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),null,null,'JURYSELECT',null,'OTHER','Other 2','test','test',now(),now(),0);