-- set schema
SET search_path TO ${POSTGRES_SCHEMA};

-- allow create of UUIDs
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- NOTE: this is a subset of the whole (only victoria and vancouver)

INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'222MAIN303','222 Main - 303','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'222MAIN100','222 Main - 100','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'222MAIN101','222 Main - 101','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'222MAIN102','222 Main - 102','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'222MAIN304','222 Main - 304','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'222MAIN305','222 Main - 305','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'222MAIN306','222 Main - 306','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'222MAIN307','222 Main - 307','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'222MAIN308','222 Main - 308','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'222MAIN309','222 Main - 309','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'222MAIN510','222 Main - 510','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'222MAIN511','222 Main - 511','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'222MAIN512','222 Main - 512','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'222MAIN513','222 Main - 513','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'222MAIN514','222 Main - 514','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'222MAIN515','222 Main - 515','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'222MAIN516','222 Main - 516','address','test','test',now(),now(),0);

INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'VICTORIA101','Victoria - 101','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'VICTORIA301','Victoria - 301','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'VICTORIA302','Victoria - 302','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'VICTORIA401','Victoria - 401','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'VICTORIA402','Victoria - 402','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'VICTORIA102','Victoria - 102','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'VICTORIA103','Victoria - 103','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'VICTORIA104','Victoria - 104','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'VICTORIA201','Victoria - 201','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'VICTORIA202','Victoria - 202','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'VICTORIA203','Victoria - 203','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'VICTORIA303','Victoria - 303','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'VICTORIA403','Victoria - 403','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'VICTORIA404','Victoria - 404','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'VICTORIA526','Victoria - 526','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'VICTORIA527','Victoria - 527','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'VICTORIA533','Victoria - 533','address','test','test',now(),now(),0);
INSERT INTO location (location_id,location_type_code,parent_location_id,location_name,description,address,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'COURTROOM',null,'VICTORIA601','Victoria - 601','address','test','test',now(),now(),0);


INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='222MAIN303'),'303',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VANCOUVER'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='222MAIN100'),'100',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VANCOUVER'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='222MAIN101'),'101',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VANCOUVER'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='222MAIN102'),'102',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VANCOUVER'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='222MAIN304'),'304',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VANCOUVER'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='222MAIN305'),'305',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VANCOUVER'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='222MAIN306'),'306',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VANCOUVER'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='222MAIN307'),'307',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VANCOUVER'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='222MAIN308'),'308',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VANCOUVER'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='222MAIN309'),'309',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VANCOUVER'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='222MAIN510'),'510',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VANCOUVER'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='222MAIN511'),'511',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VANCOUVER'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='222MAIN512'),'512',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VANCOUVER'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='222MAIN513'),'513',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VANCOUVER'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='222MAIN514'),'514',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VANCOUVER'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='222MAIN515'),'515',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VANCOUVER'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='222MAIN516'),'516',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VANCOUVER'),'test','test',now(),now(),0);

INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='VICTORIA101'),'101',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VICTORIA'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='VICTORIA301'),'301',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VICTORIA'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='VICTORIA302'),'302',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VICTORIA'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='VICTORIA401'),'401',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VICTORIA'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='VICTORIA402'),'402',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VICTORIA'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='VICTORIA102'),'102',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VICTORIA'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='VICTORIA103'),'103',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VICTORIA'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='VICTORIA104'),'104',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VICTORIA'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='VICTORIA201'),'201',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VICTORIA'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='VICTORIA202'),'202',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VICTORIA'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='VICTORIA203'),'203',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VICTORIA'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='VICTORIA303'),'303',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VICTORIA'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='VICTORIA403'),'403',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VICTORIA'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='VICTORIA404'),'404',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VICTORIA'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='VICTORIA526'),'526',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VICTORIA'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='VICTORIA527'),'527',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VICTORIA'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='VICTORIA533'),'533',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VICTORIA'),'test','test',now(),now(),0);
INSERT INTO courtroom (location_id,room_number,courthouse_location_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	((SELECT L.location_id FROM location L WHERE L.location_type_code='COURTROOM' AND L.location_name='VICTORIA601'),'601',(SELECT L.location_id FROM location L WHERE L.location_type_code='COURTHOUSE' AND L.location_name='VICTORIA'),'test','test',now(),now(),0);
