-- set schema
SET search_path TO ${POSTGRES_SCHEMA};

-- COURTROOM
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'CHILLIWACK201','Chilliwack - 201',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3521'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'CHILLIWACK202','Chilliwack - 202',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3521'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'CHILLIWACK203','Chilliwack - 203',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3521'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'CHILLIWACK204','Chilliwack - 204',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3521'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'CHILLIWACK205','Chilliwack - 205',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3521'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'CHILLIWACK200','Chilliwack - 200',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3521'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'CHILLIWACK206','Chilliwack - 206',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3521'),'test','test',now(),now(),0);

INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'ROBSONSQUARE201','Robson Square - 201',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '2045'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'ROBSONSQUARE202','Robson Square - 202',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '2045'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'ROBSONSQUARE203','Robson Square - 203',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '2045'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'ROBSONSQUARE204','Robson Square - 204',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '2045'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'ROBSONSQUARE101','Robson Square - 101',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '2045'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'ROBSONSQUARE102','Robson Square - 102',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '2045'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'ROBSONSQUARE103','Robson Square - 103',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '2045'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'ROBSONSQUARE104','Robson Square - 104',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '2045'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'ROBSONSQUARE105','Robson Square - 105',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '2045'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'ROBSONSQUARE106','Robson Square - 106',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '2045'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'ROBSONSQUARE107','Robson Square - 107',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '2045'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'ROBSONSQUARE108','Robson Square - 108',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '2045'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'ROBSONSQUARE109','Robson Square - 109',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '2045'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'ROBSONSQUARE110','Robson Square - 110',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '2045'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'ROBSONSQUARE111','Robson Square - 111',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '2045'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'ROBSONSQUARE112','Robson Square - 112',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '2045'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'ROBSONSQUARE115','Robson Square - 115',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '2045'),'test','test',now(),now(),0);

INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'SURREY100','Surrey - 100',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3585'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'SURREY101','Surrey - 101',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3585'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'SURREY102','Surrey - 102',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3585'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'SURREY103','Surrey - 103',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3585'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'SURREY104','Surrey - 104',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3585'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'SURREY105','Surrey - 105',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3585'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'SURREY106','Surrey - 106',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3585'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'SURREY107','Surrey - 107',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3585'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'SURREY300','Surrey - 300',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3585'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'SURREY301','Surrey - 301',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3585'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'SURREY308','Surrey - 308',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3585'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'SURREY309','Surrey - 309',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3585'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'SURREY310','Surrey - 310',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3585'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'SURREY311','Surrey - 311',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3585'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'SURREY312','Surrey - 312',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3585'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'SURREY313','Surrey - 313',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3585'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'SURREY314','Surrey - 314',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3585'),'test','test',now(),now(),0);

INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'VICTORIA101','Victoria - 101',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'VICTORIA301','Victoria - 301',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'VICTORIA302','Victoria - 302',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'VICTORIA401','Victoria - 401',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'VICTORIA402','Victoria - 402',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'VICTORIA102','Victoria - 102',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'VICTORIA103','Victoria - 103',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'VICTORIA104','Victoria - 104',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'VICTORIA201','Victoria - 201',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'VICTORIA202','Victoria - 202',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'VICTORIA203','Victoria - 203',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'VICTORIA303','Victoria - 303',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'VICTORIA403','Victoria - 403',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'VICTORIA404','Victoria - 404',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'VICTORIA526','Victoria - 526',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'VICTORIA527','Victoria - 527',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'VICTORIA533','Victoria - 533',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'test','test',now(),now(),0);
INSERT INTO courtroom (courtroom_id,courtroom_cd,courtroom_name,courthouse_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'VICTORIA601','Victoria - 601',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'test','test',now(),now(),0);
