-- set schema
SET search_path TO ${POSTGRES_SCHEMA};

-- DUTY_RECURRENCE
INSERT INTO duty_recurrence (duty_recurrence_id,start_time,end_time,days_bitmap,sheriffs_required,assignment_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),to_timestamp('09:00','HH24:MI'),to_timestamp('17:00','HH24:MI'),31,1,(SELECT a.assignment_id FROM assignment a WHERE a.courthouse_id = (SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201') AND a.title = 'Title 1'),'test','test',now(),now(),0);
INSERT INTO duty_recurrence (duty_recurrence_id,start_time,end_time,days_bitmap,sheriffs_required,assignment_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),to_timestamp('09:00','HH24:MI'),to_timestamp('17:00','HH24:MI'),31,2,(SELECT a.assignment_id FROM assignment a WHERE a.courthouse_id = (SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201') AND a.title = 'Title 2'),'test','test',now(),now(),0);
INSERT INTO duty_recurrence (duty_recurrence_id,start_time,end_time,days_bitmap,sheriffs_required,assignment_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),to_timestamp('09:00','HH24:MI'),to_timestamp('17:00','HH24:MI'),23,1,(SELECT a.assignment_id FROM assignment a WHERE a.courthouse_id = (SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201') AND a.title = 'Jail 1'),'test','test',now(),now(),0);
INSERT INTO duty_recurrence (duty_recurrence_id,start_time,end_time,days_bitmap,sheriffs_required,assignment_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),to_timestamp('09:00','HH24:MI'),to_timestamp('17:00','HH24:MI'),23,2,(SELECT a.assignment_id FROM assignment a WHERE a.courthouse_id = (SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201') AND a.title = 'Jail 2'),'test','test',now(),now(),0);
INSERT INTO duty_recurrence (duty_recurrence_id,start_time,end_time,days_bitmap,sheriffs_required,assignment_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),to_timestamp('09:00','HH24:MI'),to_timestamp('17:00','HH24:MI'),7,1,(SELECT a.assignment_id FROM assignment a WHERE a.courthouse_id = (SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201') AND a.title = 'Escort 1'),'test','test',now(),now(),0);
INSERT INTO duty_recurrence (duty_recurrence_id,start_time,end_time,days_bitmap,sheriffs_required,assignment_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),to_timestamp('09:00','HH24:MI'),to_timestamp('17:00','HH24:MI'),7,2,(SELECT a.assignment_id FROM assignment a WHERE a.courthouse_id = (SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201') AND a.title = 'Escort 2'),'test','test',now(),now(),0);
INSERT INTO duty_recurrence (duty_recurrence_id,start_time,end_time,days_bitmap,sheriffs_required,assignment_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),to_timestamp('09:00','HH24:MI'),to_timestamp('17:00','HH24:MI'),26,1,(SELECT a.assignment_id FROM assignment a WHERE a.courthouse_id = (SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201') AND a.title = 'Other 1'),'test','test',now(),now(),0);
INSERT INTO duty_recurrence (duty_recurrence_id,start_time,end_time,days_bitmap,sheriffs_required,assignment_id,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),to_timestamp('09:00','HH24:MI'),to_timestamp('17:00','HH24:MI'),26,2,(SELECT a.assignment_id FROM assignment a WHERE a.courthouse_id = (SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201') AND a.title = 'Other 2'),'test','test',now(),now(),0);
