-- set schema
SET search_path TO ${POSTGRES_SCHEMA};

-- SHERIFF
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10000',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'SERGEANT','userId10000','Fred','Flintstone','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10001',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'DEPUTYSHERIFF','userId10001','Wilma','Flintstone','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10002',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'DEPUTYSHERIFF','userId10002','Pebbles','Flintstone','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10003',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'STAFFSERGEANT','userId10003','Mr.','Slate','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10004',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'SERGEANT','userId10004','Betty','Rubble','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10005',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '1201'),'SERGEANT','userId10005','Barney','Rubble','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10006',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '2045'),'DEPUTYSHERIFF','userId10006','Minnie','Mouse','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10007',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '2045'),'STAFFSERGEANT','userId10007','Mickie','Mouse','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10008',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '2045'),'SERGEANT','userId10008','Donald','Duck','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10009',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3521'),'DEPUTYSHERIFF','userId10009','Bugs','Bunny','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10010',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3521'),'DEPUTYSHERIFF','userId10010','Daffy','Duck','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10011',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3521'),'SERGEANT','userId10011','Elmer','Fudd','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10012',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3585'),'INSPECTOR','userId10012','Papa','Smurf','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10013',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3585'),'SERGEANT','userId10013','Brainy','Smurf','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10014',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = '3585'),'DEPUTYSHERIFF','userId10014','Smurfette','Smurf','','test','test',now(),now(),0);
