-- set schema
SET search_path TO ${POSTGRES_SCHEMA};

-- SHERIFF
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10000',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = 'VICTORIA'),'SERGEANT','userId10000','Fred','Flintstone','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10001',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = 'VICTORIA'),'DEPUTYSHERIFF','userId10001','Wilma','Flintstone','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10002',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = 'VICTORIA'),'DEPUTYSHERIFF','userId10002','Pebbles','Flintstone','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10003',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = 'SURREY'),'STAFFSERGEANT','userId10003','Mr.','Slate','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10004',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = 'SURREY'),'INSPECTOR','userId10004','Bugs','Bunny','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10005',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = 'ROBSONSQUARE'),'SERGEANT','userId10005','Betty','Rubble','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10006',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = 'ROBSONSQUARE'),'SERGEANT','userId10006','Barney','Rubble','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10007',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = 'ROBSONSQUARE'),'DEPUTYSHERIFF','userId10007','Donald','Duck','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10008',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = 'ROBSONSQUARE'),'DEPUTYSHERIFF','userId10008','Minnie','Mouse','','test','test',now(),now(),0);
INSERT INTO sheriff (sheriff_id,badge_no,courthouse_id,sheriff_rank_code,userid,first_name,last_name,image_url,created_by,updated_by,created_dtm,updated_dtm,revision_count)	 VALUES 	(uuid_generate_v4(),'BN10009',(SELECT c.courthouse_id FROM courthouse c WHERE c.courthouse_cd = 'ROBSONSQUARE'),'STAFFSERGEANT','userId10009','Mickie','Mouse','','test','test',now(),now(),0);
