package ca.bc.gov.jag.shuber.persistence.model;

import ca.bc.gov.jag.shuber.persistence.AbstractAuditableVersionable;
import java.io.Serializable;
import java.util.Date;
import java.util.UUID;
import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * AssignmentQualificationXref generated by Hibernate Tools hbm2java.
 *
 * <p>Domain model for database table assignment_qualification_xref.
 *
 * @author hbm2java
 * @version 1.0.0.243
 */
@Entity
@Table(name = "assignment_qualification_xref"
    // ,schema="shersched"
)
@Generated(
    value = "hbm2java",
    date = "2018-02-21 07:25:02",
    comments = "Generated by Hibernate Tools hbm2java."
)
public class AssignmentQualificationXref extends AbstractAuditableVersionable
        implements Serializable {
    /** UID. */
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Column(name = "assignment_qualification_xref_id", nullable = false, updatable = false)
    private UUID assignmentQualificationXrefId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assignment_id", nullable = false)
    private Assignment assignment;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "qualification_id", nullable = false)
    private Qualification qualification;
    /** No args constructor. */
    public AssignmentQualificationXref() {}

    /** All args constructor. */
    public AssignmentQualificationXref(
            UUID assignmentQualificationXrefId,
            Assignment assignment,
            Qualification qualification,
            String createdBy,
            String updatedBy,
            Date createdDtm,
            Date updatedDtm,
            long revisionCount) {
        this.assignmentQualificationXrefId = assignmentQualificationXrefId;
        this.assignment = assignment;
        this.qualification = qualification;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
    }

    public UUID getAssignmentQualificationXrefId() {
        return this.assignmentQualificationXrefId;
    }

    public void setAssignmentQualificationXrefId(UUID assignmentQualificationXrefId) {
        this.assignmentQualificationXrefId = assignmentQualificationXrefId;
    }

    public Assignment getAssignment() {
        return this.assignment;
    }

    public void setAssignment(Assignment assignment) {
        this.assignment = assignment;
    }

    public Qualification getQualification() {
        return this.qualification;
    }

    public void setQualification(Qualification qualification) {
        this.qualification = qualification;
    }
}
