package ca.bc.gov.jag.shuber.persistence.model;

import ca.bc.gov.jag.shuber.persistence.AbstractAuditableVersionable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * AssignmentCode generated by Hibernate Tools hbm2java.
 *
 * <p>Domain model for database table assignment_code.
 *
 * @author hbm2java
 * @version 344
 */
@Entity
@Table(name = "assignment_code"
    // ,schema="shersched"
)
public class AssignmentCode extends AbstractAuditableVersionable implements Serializable {

    /** UID. */
    private static final long serialVersionUID = 1L;

    @Id
    @Size(min = 1, max = 20)
    @Column(name = "assignment_code", nullable = false, updatable = false, length = 20)
    private String assignmentCode;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "work_section_code")
    private WorkSectionCode workSectionCode;

    @NotEmpty
    @Size(min = 1, max = 255)
    @Column(name = "description", nullable = false)
    private String description;

    @NotNull
    @Temporal(TemporalType.DATE)
    @Column(name = "effective_date", nullable = false, length = 13)
    private Date effectiveDate;

    @Temporal(TemporalType.DATE)
    @Column(name = "expiry_date", length = 13)
    private Date expiryDate;

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "assignmentCode")
    private List<AssignmentStream> assignmentStreams = new ArrayList<AssignmentStream>(0);
    /** No args constructor. */
    public AssignmentCode() {}

    /** Required args constructor. */
    public AssignmentCode(
            String assignmentCode,
            String description,
            Date effectiveDate,
            String createdBy,
            String updatedBy,
            Date createdDtm,
            Date updatedDtm,
            long revisionCount) {
        this.assignmentCode = assignmentCode;
        this.description = description;
        this.effectiveDate = effectiveDate;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
    }

    /** All args constructor. */
    public AssignmentCode(
            String assignmentCode,
            WorkSectionCode workSectionCode,
            String description,
            Date effectiveDate,
            Date expiryDate,
            String createdBy,
            String updatedBy,
            Date createdDtm,
            Date updatedDtm,
            long revisionCount,
            List<AssignmentStream> assignmentStreams) {
        this.assignmentCode = assignmentCode;
        this.workSectionCode = workSectionCode;
        this.description = description;
        this.effectiveDate = effectiveDate;
        this.expiryDate = expiryDate;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
        this.assignmentStreams = assignmentStreams;
    }

    public String getAssignmentCode() {
        return this.assignmentCode;
    }

    public void setAssignmentCode(String assignmentCode) {
        this.assignmentCode = assignmentCode;
    }

    public WorkSectionCode getWorkSectionCode() {
        return this.workSectionCode;
    }

    public void setWorkSectionCode(WorkSectionCode workSectionCode) {
        this.workSectionCode = workSectionCode;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Date getEffectiveDate() {
        return this.effectiveDate;
    }

    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    public Date getExpiryDate() {
        return this.expiryDate;
    }

    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    public List<AssignmentStream> getAssignmentStreams() {
        return this.assignmentStreams;
    }

    public void setAssignmentStreams(List<AssignmentStream> assignmentStreams) {
        this.assignmentStreams = assignmentStreams;
    }
}
