package ca.bc.gov.jag.shuber.persistence.model;

import ca.bc.gov.jag.shuber.persistence.AbstractAuditableVersionable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Courthouse generated by Hibernate Tools hbm2java.
 *
 * <p>Domain model for database table courthouse.
 *
 * @author hbm2java
 * @version 1.0.0.243
 */
@Entity
@Table(name = "courthouse"
    // ,schema="shersched"
)
@Generated(
    value = "hbm2java",
    date = "2018-02-21 07:25:02",
    comments = "Generated by Hibernate Tools hbm2java."
)
public class Courthouse extends AbstractAuditableVersionable implements Serializable {
    /** UID. */
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Column(name = "location_id", nullable = false, updatable = false)
    private UUID locationId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "region_location_id")
    private Region region;

    @Column(name = "courthouse_type_code", nullable = false)
    private String courthouseTypeCode;

    @Column(name = "org_unit_id", nullable = false)
    private UUID orgUnitId;

    @Column(name = "geometry")
    private UUID geometry;

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "courthouse")
    private List<Courtroom> courtrooms = new ArrayList<Courtroom>(0);
    /** No args constructor. */
    public Courthouse() {}

    /** Required args constructor. */
    public Courthouse(
            UUID locationId,
            String courthouseTypeCode,
            UUID orgUnitId,
            String createdBy,
            String updatedBy,
            Date createdDtm,
            Date updatedDtm,
            long revisionCount) {
        this.locationId = locationId;
        this.courthouseTypeCode = courthouseTypeCode;
        this.orgUnitId = orgUnitId;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
    }

    /** All args constructor. */
    public Courthouse(
            UUID locationId,
            Region region,
            String courthouseTypeCode,
            UUID orgUnitId,
            UUID geometry,
            String createdBy,
            String updatedBy,
            Date createdDtm,
            Date updatedDtm,
            long revisionCount,
            List<Courtroom> courtrooms) {
        this.locationId = locationId;
        this.region = region;
        this.courthouseTypeCode = courthouseTypeCode;
        this.orgUnitId = orgUnitId;
        this.geometry = geometry;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
        this.courtrooms = courtrooms;
    }

    public UUID getLocationId() {
        return this.locationId;
    }

    public void setLocationId(UUID locationId) {
        this.locationId = locationId;
    }

    public Region getRegion() {
        return this.region;
    }

    public void setRegion(Region region) {
        this.region = region;
    }

    public String getCourthouseTypeCode() {
        return this.courthouseTypeCode;
    }

    public void setCourthouseTypeCode(String courthouseTypeCode) {
        this.courthouseTypeCode = courthouseTypeCode;
    }

    public UUID getOrgUnitId() {
        return this.orgUnitId;
    }

    public void setOrgUnitId(UUID orgUnitId) {
        this.orgUnitId = orgUnitId;
    }

    public UUID getGeometry() {
        return this.geometry;
    }

    public void setGeometry(UUID geometry) {
        this.geometry = geometry;
    }

    public List<Courtroom> getCourtrooms() {
        return this.courtrooms;
    }

    public void setCourtrooms(List<Courtroom> courtrooms) {
        this.courtrooms = courtrooms;
    }
}
