package ca.bc.gov.jag.shuber.persistence.model;

import ca.bc.gov.jag.shuber.persistence.AbstractAuditableVersionable;
import java.io.Serializable;
import java.util.Date;
import java.util.UUID;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * Duty generated by Hibernate Tools hbm2java.
 *
 * <p>Domain model for database table duty.
 *
 * @author hbm2java
 * @version 352
 */
@Entity
@Table(name = "duty"
    // ,schema="shersched"
)
public class Duty extends AbstractAuditableVersionable implements Serializable {

    /** UID. */
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Column(name = "duty_id", nullable = false, updatable = false)
    private UUID dutyId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assignment_stream_id")
    private AssignmentStream assignmentStream;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assignment_template_id")
    private DutyTemplate dutyTemplate;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "shift_id")
    private Shift shift;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "work_section_code")
    private WorkSectionCode workSectionCode;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "start_time", length = 35)
    private Date startTime;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "end_time", length = 35)
    private Date endTime;
    
    /** No args constructor. */
    public Duty() {}

    /** Required args constructor. */
    public Duty(
            UUID dutyId,
            String createdBy,
            String updatedBy,
            Date createdDtm,
            Date updatedDtm,
            long revisionCount) {
        this.dutyId = dutyId;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
    }

    /** All args constructor. */
    public Duty(
            UUID dutyId,
            AssignmentStream assignmentStream,
            DutyTemplate dutyTemplate,
            Shift shift,
            WorkSectionCode workSectionCode,
            Date startTime,
            Date endTime,
            String createdBy,
            String updatedBy,
            Date createdDtm,
            Date updatedDtm,
            long revisionCount) {
        this.dutyId = dutyId;
        this.assignmentStream = assignmentStream;
        this.dutyTemplate = dutyTemplate;
        this.shift = shift;
        this.workSectionCode = workSectionCode;
        this.startTime = startTime;
        this.endTime = endTime;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
    }

    public UUID getDutyId() {
        return this.dutyId;
    }

    public void setDutyId(UUID dutyId) {
        this.dutyId = dutyId;
    }

    public AssignmentStream getAssignmentStream() {
        return this.assignmentStream;
    }

    public void setAssignmentStream(AssignmentStream assignmentStream) {
        this.assignmentStream = assignmentStream;
    }

    public DutyTemplate getDutyTemplate() {
        return this.dutyTemplate;
    }

    public void setDutyTemplate(DutyTemplate dutyTemplate) {
        this.dutyTemplate = dutyTemplate;
    }

    public Shift getShift() {
        return this.shift;
    }

    public void setShift(Shift shift) {
        this.shift = shift;
    }

    public WorkSectionCode getWorkSectionCode() {
        return this.workSectionCode;
    }

    public void setWorkSectionCode(WorkSectionCode workSectionCode) {
        this.workSectionCode = workSectionCode;
    }

    public Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}
