package ca.bc.gov.jag.shuber.persistence.model;

import ca.bc.gov.jag.shuber.persistence.AbstractAuditableVersionable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

/**
 * Qualification generated by Hibernate Tools hbm2java.
 *
 * <p>Domain model for database table qualification.
 *
 * @author hbm2java
 * @version 1.0.0.243
 */
@Entity
@Table(name = "qualification"
    // ,schema="shersched"
)
@Generated(
    value = "hbm2java",
    date = "2018-02-21 07:25:02",
    comments = "Generated by Hibernate Tools hbm2java."
)
public class Qualification extends AbstractAuditableVersionable implements Serializable {
    /** UID. */
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Column(name = "qualification_id", nullable = false, updatable = false)
    private UUID qualificationId;

    @Column(name = "qualification_type_code", nullable = false, length = 20)
    private String qualificationTypeCode;

    @Type(type = "yes_no")
    @Column(name = "required_for_all_flag", nullable = false, length = 1)
    private Boolean requiredForAllFlag;

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "qualification")
    private List<SheriffQualificationXref> sheriffQualificationXrefs =
            new ArrayList<SheriffQualificationXref>(0);

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "qualification")
    private List<AssignmentQualificationXref> assignmentQualificationXrefs =
            new ArrayList<AssignmentQualificationXref>(0);
    /** No args constructor. */
    public Qualification() {}

    /** Required args constructor. */
    public Qualification(
            UUID qualificationId,
            String qualificationTypeCode,
            Boolean requiredForAllFlag,
            String createdBy,
            String updatedBy,
            Date createdDtm,
            Date updatedDtm,
            long revisionCount) {
        this.qualificationId = qualificationId;
        this.qualificationTypeCode = qualificationTypeCode;
        this.requiredForAllFlag = requiredForAllFlag;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
    }

    /** All args constructor. */
    public Qualification(
            UUID qualificationId,
            String qualificationTypeCode,
            Boolean requiredForAllFlag,
            String createdBy,
            String updatedBy,
            Date createdDtm,
            Date updatedDtm,
            long revisionCount,
            List<SheriffQualificationXref> sheriffQualificationXrefs,
            List<AssignmentQualificationXref> assignmentQualificationXrefs) {
        this.qualificationId = qualificationId;
        this.qualificationTypeCode = qualificationTypeCode;
        this.requiredForAllFlag = requiredForAllFlag;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
        this.sheriffQualificationXrefs = sheriffQualificationXrefs;
        this.assignmentQualificationXrefs = assignmentQualificationXrefs;
    }

    public UUID getQualificationId() {
        return this.qualificationId;
    }

    public void setQualificationId(UUID qualificationId) {
        this.qualificationId = qualificationId;
    }

    public String getQualificationTypeCode() {
        return this.qualificationTypeCode;
    }

    public void setQualificationTypeCode(String qualificationTypeCode) {
        this.qualificationTypeCode = qualificationTypeCode;
    }

    public Boolean getRequiredForAllFlag() {
        return this.requiredForAllFlag;
    }

    public void setRequiredForAllFlag(Boolean requiredForAllFlag) {
        this.requiredForAllFlag = requiredForAllFlag;
    }

    public List<SheriffQualificationXref> getSheriffQualificationXrefs() {
        return this.sheriffQualificationXrefs;
    }

    public void setSheriffQualificationXrefs(
            List<SheriffQualificationXref> sheriffQualificationXrefs) {
        this.sheriffQualificationXrefs = sheriffQualificationXrefs;
    }

    public List<AssignmentQualificationXref> getAssignmentQualificationXrefs() {
        return this.assignmentQualificationXrefs;
    }

    public void setAssignmentQualificationXrefs(
            List<AssignmentQualificationXref> assignmentQualificationXrefs) {
        this.assignmentQualificationXrefs = assignmentQualificationXrefs;
    }
}
