package ca.bc.gov.jag.shuber.persistence.model;

import ca.bc.gov.jag.shuber.persistence.AbstractAuditableVersionable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Sheriff generated by Hibernate Tools hbm2java.
 *
 * <p>Domain model for database table sheriff.
 *
 * @author hbm2java
 * @version 1.0.0.243
 */
@Entity
@Table(name = "sheriff"
    // ,schema="shersched"
)
@Generated(
    value = "hbm2java",
    date = "2018-02-21 07:25:02",
    comments = "Generated by Hibernate Tools hbm2java."
)
public class Sheriff extends AbstractAuditableVersionable implements Serializable {
    /** UID. */
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Column(name = "sheriff_id", nullable = false, updatable = false)
    private UUID sheriffId;

    @Column(name = "badge_no", unique = true, nullable = false, length = 20)
    private String badgeNo;

    @Column(name = "name", length = 100)
    private String name;

    @Column(name = "default_location_id")
    private UUID defaultLocationId;

    @Column(name = "rank", length = 50)
    private String rank;

    @Column(name = "org_unit_id")
    private UUID orgUnitId;

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sheriff")
    private List<Shift> shifts = new ArrayList<Shift>(0);

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sheriff")
    private List<SheriffQualificationXref> sheriffQualificationXrefs =
            new ArrayList<SheriffQualificationXref>(0);
    /** No args constructor. */
    public Sheriff() {}

    /** Required args constructor. */
    public Sheriff(
            UUID sheriffId,
            String badgeNo,
            String createdBy,
            String updatedBy,
            Date createdDtm,
            Date updatedDtm,
            long revisionCount) {
        this.sheriffId = sheriffId;
        this.badgeNo = badgeNo;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
    }

    /** All args constructor. */
    public Sheriff(
            UUID sheriffId,
            String badgeNo,
            String name,
            UUID defaultLocationId,
            String rank,
            UUID orgUnitId,
            String createdBy,
            String updatedBy,
            Date createdDtm,
            Date updatedDtm,
            long revisionCount,
            List<Shift> shifts,
            List<SheriffQualificationXref> sheriffQualificationXrefs) {
        this.sheriffId = sheriffId;
        this.badgeNo = badgeNo;
        this.name = name;
        this.defaultLocationId = defaultLocationId;
        this.rank = rank;
        this.orgUnitId = orgUnitId;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
        this.shifts = shifts;
        this.sheriffQualificationXrefs = sheriffQualificationXrefs;
    }

    public UUID getSheriffId() {
        return this.sheriffId;
    }

    public void setSheriffId(UUID sheriffId) {
        this.sheriffId = sheriffId;
    }

    public String getBadgeNo() {
        return this.badgeNo;
    }

    public void setBadgeNo(String badgeNo) {
        this.badgeNo = badgeNo;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public UUID getDefaultLocationId() {
        return this.defaultLocationId;
    }

    public void setDefaultLocationId(UUID defaultLocationId) {
        this.defaultLocationId = defaultLocationId;
    }

    public String getRank() {
        return this.rank;
    }

    public void setRank(String rank) {
        this.rank = rank;
    }

    public UUID getOrgUnitId() {
        return this.orgUnitId;
    }

    public void setOrgUnitId(UUID orgUnitId) {
        this.orgUnitId = orgUnitId;
    }

    public List<Shift> getShifts() {
        return this.shifts;
    }

    public void setShifts(List<Shift> shifts) {
        this.shifts = shifts;
    }

    public List<SheriffQualificationXref> getSheriffQualificationXrefs() {
        return this.sheriffQualificationXrefs;
    }

    public void setSheriffQualificationXrefs(
            List<SheriffQualificationXref> sheriffQualificationXrefs) {
        this.sheriffQualificationXrefs = sheriffQualificationXrefs;
    }
}
