package ca.bc.gov.jag.shuber.persistence.model;

import java.io.Serializable;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.hibernate.annotations.Type;

/**
 * SheriffQualificationXrefId generated by Hibernate Tools hbm2java.
 *
 * <p>Domain model for database table sheriff_qualification_xref.
 *
 * @author hbm2java
 * @version 1.0.0.242
 */
@Embeddable
public class SheriffQualificationXrefId implements Serializable {
    /** UID. */
    private static final long serialVersionUID = 1L;

    @Type(type = "uuid-binary")
    @Column(name = "qualification_id", nullable = false, updatable = false)
    private UUID qualificationId;

    @Type(type = "uuid-binary")
    @Column(name = "sheriff_id", nullable = false, updatable = false)
    private UUID sheriffId;
    /** No args constructor. */
    public SheriffQualificationXrefId() {}

    /** All args constructor. */
    public SheriffQualificationXrefId(UUID qualificationId, UUID sheriffId) {
        this.qualificationId = qualificationId;
        this.sheriffId = sheriffId;
    }

    public UUID getQualificationId() {
        return this.qualificationId;
    }

    public void setQualificationId(UUID qualificationId) {
        this.qualificationId = qualificationId;
    }

    public UUID getSheriffId() {
        return this.sheriffId;
    }

    public void setSheriffId(UUID sheriffId) {
        this.sheriffId = sheriffId;
    }
}
