package ca.bc.gov.jag.shuber.persistence.model;

import ca.bc.gov.jag.shuber.persistence.AbstractAuditableVersionable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Type;

/**
 * Shift generated by Hibernate Tools hbm2java.
 *
 * <p>Domain model for database table shift.
 *
 * @author hbm2java
 * @version 1.0.0.243
 */
@Entity
@Table(name = "shift"
    // ,schema="shersched"
)
@Generated(
    value = "hbm2java",
    date = "2018-02-21 07:25:02",
    comments = "Generated by Hibernate Tools hbm2java."
)
public class Shift extends AbstractAuditableVersionable implements Serializable {
    /** UID. */
    private static final long serialVersionUID = 1L;

    @Id
    @Column(name = "shift_id", nullable = false, updatable = false)
    private int shiftId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sheriff_id")
    private Sheriff sheriff;

    @Column(name = "shift_status")
    private String shiftStatus;

    @Temporal(TemporalType.DATE)
    @Column(name = "shift_date", length = 13)
    private Date shiftDate;

    @Temporal(TemporalType.TIME)
    @Column(name = "shift_start_time", length = 15)
    private Date shiftStartTime;

    @Type(type = "yes_no")
    @Column(name = "rotation_template_flag", nullable = false, length = 1)
    private Boolean rotationTemplateFlag;

    @Column(name = "org_unit_id")
    private UUID orgUnitId;

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "shift")
    private List<AssignmentBlock> assignmentBlocks = new ArrayList<AssignmentBlock>(0);
    /** No args constructor. */
    public Shift() {}

    /** Required args constructor. */
    public Shift(
            int shiftId,
            Boolean rotationTemplateFlag,
            String createdBy,
            String updatedBy,
            Date createdDtm,
            Date updatedDtm,
            long revisionCount) {
        this.shiftId = shiftId;
        this.rotationTemplateFlag = rotationTemplateFlag;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
    }

    /** All args constructor. */
    public Shift(
            int shiftId,
            Sheriff sheriff,
            String shiftStatus,
            Date shiftDate,
            Date shiftStartTime,
            Boolean rotationTemplateFlag,
            UUID orgUnitId,
            String createdBy,
            String updatedBy,
            Date createdDtm,
            Date updatedDtm,
            long revisionCount,
            List<AssignmentBlock> assignmentBlocks) {
        this.shiftId = shiftId;
        this.sheriff = sheriff;
        this.shiftStatus = shiftStatus;
        this.shiftDate = shiftDate;
        this.shiftStartTime = shiftStartTime;
        this.rotationTemplateFlag = rotationTemplateFlag;
        this.orgUnitId = orgUnitId;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
        this.assignmentBlocks = assignmentBlocks;
    }

    public int getShiftId() {
        return this.shiftId;
    }

    public void setShiftId(int shiftId) {
        this.shiftId = shiftId;
    }

    public Sheriff getSheriff() {
        return this.sheriff;
    }

    public void setSheriff(Sheriff sheriff) {
        this.sheriff = sheriff;
    }

    public String getShiftStatus() {
        return this.shiftStatus;
    }

    public void setShiftStatus(String shiftStatus) {
        this.shiftStatus = shiftStatus;
    }

    public Date getShiftDate() {
        return this.shiftDate;
    }

    public void setShiftDate(Date shiftDate) {
        this.shiftDate = shiftDate;
    }

    public Date getShiftStartTime() {
        return this.shiftStartTime;
    }

    public void setShiftStartTime(Date shiftStartTime) {
        this.shiftStartTime = shiftStartTime;
    }

    public Boolean getRotationTemplateFlag() {
        return this.rotationTemplateFlag;
    }

    public void setRotationTemplateFlag(Boolean rotationTemplateFlag) {
        this.rotationTemplateFlag = rotationTemplateFlag;
    }

    public UUID getOrgUnitId() {
        return this.orgUnitId;
    }

    public void setOrgUnitId(UUID orgUnitId) {
        this.orgUnitId = orgUnitId;
    }

    public List<AssignmentBlock> getAssignmentBlocks() {
        return this.assignmentBlocks;
    }

    public void setAssignmentBlocks(List<AssignmentBlock> assignmentBlocks) {
        this.assignmentBlocks = assignmentBlocks;
    }
}
