package ca.bc.gov.jag.shuber.persistence.model;

import ca.bc.gov.jag.shuber.persistence.AbstractAuditableVersionable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkSectionCode generated by Hibernate Tools hbm2java.
 *
 * <p>Domain model for database table work_section_code.
 *
 * @author hbm2java
 * @version 1.0.0.243
 */
@Entity
@Table(name = "work_section_code"
    // ,schema="shersched"
)
@Generated(
    value = "hbm2java",
    date = "2018-02-21 07:25:02",
    comments = "Generated by Hibernate Tools hbm2java."
)
public class WorkSectionCode extends AbstractAuditableVersionable implements Serializable {
    /** UID. */
    private static final long serialVersionUID = 1L;

    @Id
    @Column(name = "work_section_code", nullable = false, updatable = false, length = 20)
    private String workSectionCode;

    @Column(name = "work_section_description", length = 100)
    private String workSectionDescription;

    @Temporal(TemporalType.DATE)
    @Column(name = "effective_date", nullable = false, length = 13)
    private Date effectiveDate;

    @Temporal(TemporalType.DATE)
    @Column(name = "expiry_date", length = 13)
    private Date expiryDate;

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "workSectionCode")
    private List<AssignmentBlock> assignmentBlocks = new ArrayList<AssignmentBlock>(0);

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "workSectionCode")
    private List<AssignmentTypeCode> assignmentTypeCodes = new ArrayList<AssignmentTypeCode>(0);
    /** No args constructor. */
    public WorkSectionCode() {}

    /** Required args constructor. */
    public WorkSectionCode(
            String workSectionCode,
            Date effectiveDate,
            String createdBy,
            String updatedBy,
            Date createdDtm,
            Date updatedDtm,
            long revisionCount) {
        this.workSectionCode = workSectionCode;
        this.effectiveDate = effectiveDate;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
    }

    /** All args constructor. */
    public WorkSectionCode(
            String workSectionCode,
            String workSectionDescription,
            Date effectiveDate,
            Date expiryDate,
            String createdBy,
            String updatedBy,
            Date createdDtm,
            Date updatedDtm,
            long revisionCount,
            List<AssignmentBlock> assignmentBlocks,
            List<AssignmentTypeCode> assignmentTypeCodes) {
        this.workSectionCode = workSectionCode;
        this.workSectionDescription = workSectionDescription;
        this.effectiveDate = effectiveDate;
        this.expiryDate = expiryDate;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdDtm = createdDtm;
        this.updatedDtm = updatedDtm;
        this.revisionCount = revisionCount;
        this.assignmentBlocks = assignmentBlocks;
        this.assignmentTypeCodes = assignmentTypeCodes;
    }

    public String getWorkSectionCode() {
        return this.workSectionCode;
    }

    public void setWorkSectionCode(String workSectionCode) {
        this.workSectionCode = workSectionCode;
    }

    public String getWorkSectionDescription() {
        return this.workSectionDescription;
    }

    public void setWorkSectionDescription(String workSectionDescription) {
        this.workSectionDescription = workSectionDescription;
    }

    public Date getEffectiveDate() {
        return this.effectiveDate;
    }

    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    public Date getExpiryDate() {
        return this.expiryDate;
    }

    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    public List<AssignmentBlock> getAssignmentBlocks() {
        return this.assignmentBlocks;
    }

    public void setAssignmentBlocks(List<AssignmentBlock> assignmentBlocks) {
        this.assignmentBlocks = assignmentBlocks;
    }

    public List<AssignmentTypeCode> getAssignmentTypeCodes() {
        return this.assignmentTypeCodes;
    }

    public void setAssignmentTypeCodes(List<AssignmentTypeCode> assignmentTypeCodes) {
        this.assignmentTypeCodes = assignmentTypeCodes;
    }
}
