/*****************************AutoGenerated Code : Do not edit *******************************/
// Type generated from Swagger definition

import * as superAgent from "superagent";
import { Assignment,Region,Courthouse,Sheriff,Courtroom,JailRoleCode,OtherAssignCode,WorkSectionCode,SheriffRankCode,Run,Shift,MultipleShiftUpdateRequest,ShiftCopyOptions,DutyRecurrence,Duty,DutyImportDefaultsRequest,SheriffDuty,Leave,LeaveCancelReasonCode,LeaveCode,LeaveSubCode,CourtRoleCode,GenderCode } from "./models"


export default class Client {
    public errorProcessor: (error:any) => Error = (e)=>e;
    
    constructor(private _agent:superAgent.SuperAgent<any> = superAgent.agent()){
    }

    get agent(){
        return this._agent;
    }

    async tryWork<T>(worker: () => Promise<T>) {
        try {
            const result = await worker();
            return result;
        } catch (error) {
            if (this.errorProcessor) {
                throw this.errorProcessor(error);
            } else {
                throw error;
            }
        }
    }

    public async GetAssignments( courthouseId:string , startDate:string , endDate:string ):Promise<Array<any>>{
        const params = { 
            "courthouseId":courthouseId,
            "startDate":startDate,
            "endDate":endDate 
        };
        return this.tryWork(async () => {
            const response = await this.agent.get(`/Assignments`)
                .query(params)
            return response.body as Array<any>;
        });
    }    
    public async CreateAssignment( model:Assignment ):Promise<Assignment>{
        return this.tryWork(async () => {
            const response = await this.agent.post(`/Assignments`)
                .send(model)
            return response.body as Assignment;
        });
    }    
    public async GetAssignmentById( id:string ):Promise<Assignment>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/Assignments/${id}`)
            return response.body as Assignment;
        });
    }    
    public async UpdateAssignment( id:string , model:Assignment ):Promise<Assignment>{
        return this.tryWork(async () => {
            const response = await this.agent.put(`/Assignments/${id}`)
                .send(model)
            return response.body as Assignment;
        });
    }    
    public async ExpireAssignment( id:string ):Promise<void>{
        return this.tryWork(async () => {
            const response = await this.agent.post(`/Assignments/${id}`)
            return response.body as void;
        });
    }    
    public async DeleteAssignment( id:string ):Promise<void>{
        return this.tryWork(async () => {
            const response = await this.agent.delete(`/Assignments/${id}`)
            return response.body as void;
        });
    }    
    public async GetRegions():Promise<Array<Region>>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/regions`)
            return response.body as Array<Region>;
        });
    }    
    public async CreateRegion( model:Region ):Promise<Region>{
        return this.tryWork(async () => {
            const response = await this.agent.post(`/regions`)
                .send(model)
            return response.body as Region;
        });
    }    
    public async GetRegionById( id:string ):Promise<Region>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/regions/${id}`)
            return response.body as Region;
        });
    }    
    public async UpdateRegion( id:string , model:Region ):Promise<Region>{
        return this.tryWork(async () => {
            const response = await this.agent.put(`/regions/${id}`)
                .send(model)
            return response.body as Region;
        });
    }    
    public async DeleteRegion( id:string ):Promise<void>{
        return this.tryWork(async () => {
            const response = await this.agent.delete(`/regions/${id}`)
            return response.body as void;
        });
    }    
    public async GetCourthouses():Promise<Array<Courthouse>>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/courthouses`)
            return response.body as Array<Courthouse>;
        });
    }    
    public async CreateCourthouse( model:Courthouse ):Promise<Courthouse>{
        return this.tryWork(async () => {
            const response = await this.agent.post(`/courthouses`)
                .send(model)
            return response.body as Courthouse;
        });
    }    
    public async GetCourthouseById( id:string ):Promise<Courthouse>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/courthouses/${id}`)
            return response.body as Courthouse;
        });
    }    
    public async UpdateCourthouse( id:string , model:Courthouse ):Promise<Courthouse>{
        return this.tryWork(async () => {
            const response = await this.agent.put(`/courthouses/${id}`)
                .send(model)
            return response.body as Courthouse;
        });
    }    
    public async DeleteCourthouse( id:string ):Promise<void>{
        return this.tryWork(async () => {
            const response = await this.agent.delete(`/courthouses/${id}`)
            return response.body as void;
        });
    }    
    public async GetSheriffs( courthouseId:string ):Promise<Array<Sheriff>>{
        const params = { 
            "courthouseId":courthouseId 
        };
        return this.tryWork(async () => {
            const response = await this.agent.get(`/sheriffs`)
                .query(params)
            return response.body as Array<Sheriff>;
        });
    }    
    public async CreateSheriff( model:Sheriff ):Promise<Sheriff>{
        return this.tryWork(async () => {
            const response = await this.agent.post(`/sheriffs`)
                .send(model)
            return response.body as Sheriff;
        });
    }    
    public async GetSheriffById( id:string ):Promise<Sheriff>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/sheriffs/${id}`)
            return response.body as Sheriff;
        });
    }    
    public async UpdateSheriff( id:string , model:Sheriff ):Promise<Sheriff>{
        return this.tryWork(async () => {
            const response = await this.agent.put(`/sheriffs/${id}`)
                .send(model)
            return response.body as Sheriff;
        });
    }    
    public async DeleteSheriff( id:string ):Promise<void>{
        return this.tryWork(async () => {
            const response = await this.agent.delete(`/sheriffs/${id}`)
            return response.body as void;
        });
    }    
    public async GetCourtrooms( courthouseId:string ):Promise<Array<Courtroom>>{
        const params = { 
            "courthouseId":courthouseId 
        };
        return this.tryWork(async () => {
            const response = await this.agent.get(`/courtrooms`)
                .query(params)
            return response.body as Array<Courtroom>;
        });
    }    
    public async CreateCourtroom( model:Courtroom ):Promise<Courtroom>{
        return this.tryWork(async () => {
            const response = await this.agent.post(`/courtrooms`)
                .send(model)
            return response.body as Courtroom;
        });
    }    
    public async GetCourtroomById( id:string ):Promise<Courtroom>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/courtrooms/${id}`)
            return response.body as Courtroom;
        });
    }    
    public async UpdateCourtroom( id:string , model:Courtroom ):Promise<Courtroom>{
        return this.tryWork(async () => {
            const response = await this.agent.put(`/courtrooms/${id}`)
                .send(model)
            return response.body as Courtroom;
        });
    }    
    public async DeleteCourtroom( id:string ):Promise<void>{
        return this.tryWork(async () => {
            const response = await this.agent.delete(`/courtrooms/${id}`)
            return response.body as void;
        });
    }    
    public async GetJailRoleCodes():Promise<Array<JailRoleCode>>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/codes/jailroles`)
            return response.body as Array<JailRoleCode>;
        });
    }    
    public async GetOtherAssignCodes():Promise<Array<OtherAssignCode>>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/codes/otherassign`)
            return response.body as Array<OtherAssignCode>;
        });
    }    
    public async GetWorkSectionCodes():Promise<Array<WorkSectionCode>>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/codes/worksection`)
            return response.body as Array<WorkSectionCode>;
        });
    }    
    public async GetSheriffRankCodes():Promise<Array<SheriffRankCode>>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/codes/sheriffrank`)
            return response.body as Array<SheriffRankCode>;
        });
    }    
    public async GetRuns( courthouseId:string ):Promise<Array<Run>>{
        const params = { 
            "courthouseId":courthouseId 
        };
        return this.tryWork(async () => {
            const response = await this.agent.get(`/runs`)
                .query(params)
            return response.body as Array<Run>;
        });
    }    
    public async CreateRun( model:Run ):Promise<Run>{
        return this.tryWork(async () => {
            const response = await this.agent.post(`/runs`)
                .send(model)
            return response.body as Run;
        });
    }    
    public async GetRunById( id:string ):Promise<Run>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/runs/${id}`)
            return response.body as Run;
        });
    }    
    public async UpdateRun( id:string , model:Run ):Promise<Run>{
        return this.tryWork(async () => {
            const response = await this.agent.put(`/runs/${id}`)
                .send(model)
            return response.body as Run;
        });
    }    
    public async DeleteRun( id:string ):Promise<void>{
        return this.tryWork(async () => {
            const response = await this.agent.delete(`/runs/${id}`)
            return response.body as void;
        });
    }    
    public async GetShifts( courthouseId:string ):Promise<Array<Shift>>{
        const params = { 
            "courthouseId":courthouseId 
        };
        return this.tryWork(async () => {
            const response = await this.agent.get(`/Shifts`)
                .query(params)
            return response.body as Array<Shift>;
        });
    }    
    public async CreateShift( model:Shift ):Promise<Shift>{
        return this.tryWork(async () => {
            const response = await this.agent.post(`/Shifts`)
                .send(model)
            return response.body as Shift;
        });
    }    
    public async GetShiftById( id:string ):Promise<Shift>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/Shifts/${id}`)
            return response.body as Shift;
        });
    }    
    public async UpdateShift( id:string , model:Shift ):Promise<Shift>{
        return this.tryWork(async () => {
            const response = await this.agent.put(`/Shifts/${id}`)
                .send(model)
            return response.body as Shift;
        });
    }    
    public async DeleteShift( id:string ):Promise<void>{
        return this.tryWork(async () => {
            const response = await this.agent.delete(`/Shifts/${id}`)
            return response.body as void;
        });
    }    
    public async UpdateMultipleShifts( model:MultipleShiftUpdateRequest ):Promise<Array<Shift>>{
        return this.tryWork(async () => {
            const response = await this.agent.post(`/Shifts/multiple`)
                .send(model)
            return response.body as Array<Shift>;
        });
    }    
    public async CopyShifts( model:ShiftCopyOptions ):Promise<Array<Shift>>{
        return this.tryWork(async () => {
            const response = await this.agent.post(`/Shifts/copy`)
                .send(model)
            return response.body as Array<Shift>;
        });
    }    
    public async GetDutyRecurrences( startDate:string , endDate:string ):Promise<Array<DutyRecurrence>>{
        const params = { 
            "startDate":startDate,
            "endDate":endDate 
        };
        return this.tryWork(async () => {
            const response = await this.agent.get(`/DutyRecurrences`)
                .query(params)
            return response.body as Array<DutyRecurrence>;
        });
    }    
    public async CreateDutyRecurrence( model:DutyRecurrence ):Promise<DutyRecurrence>{
        return this.tryWork(async () => {
            const response = await this.agent.post(`/DutyRecurrences`)
                .send(model)
            return response.body as DutyRecurrence;
        });
    }    
    public async GetDutyRecurrenceById( id:string ):Promise<DutyRecurrence>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/DutyRecurrences/${id}`)
            return response.body as DutyRecurrence;
        });
    }    
    public async UpdateDutyRecurrence( id:string , model:DutyRecurrence ):Promise<DutyRecurrence>{
        return this.tryWork(async () => {
            const response = await this.agent.put(`/DutyRecurrences/${id}`)
                .send(model)
            return response.body as DutyRecurrence;
        });
    }    
    public async ExpireDutyRecurrence( id:string ):Promise<void>{
        return this.tryWork(async () => {
            const response = await this.agent.post(`/DutyRecurrences/${id}`)
            return response.body as void;
        });
    }    
    public async DeleteDutyRecurrence( id:string ):Promise<void>{
        return this.tryWork(async () => {
            const response = await this.agent.delete(`/DutyRecurrences/${id}`)
            return response.body as void;
        });
    }    
    public async GetDuties():Promise<Array<any>>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/Duty`)
            return response.body as Array<any>;
        });
    }    
    public async CreateDuty( model:Duty ):Promise<Duty>{
        return this.tryWork(async () => {
            const response = await this.agent.post(`/Duty`)
                .send(model)
            return response.body as Duty;
        });
    }    
    public async GetDutyById( id:string ):Promise<Duty>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/Duty/${id}`)
            return response.body as Duty;
        });
    }    
    public async UpdateDuty( id:string , model:Duty ):Promise<Duty>{
        return this.tryWork(async () => {
            const response = await this.agent.put(`/Duty/${id}`)
                .send(model)
            return response.body as Duty;
        });
    }    
    public async DeleteDuty( id:string ):Promise<void>{
        return this.tryWork(async () => {
            const response = await this.agent.delete(`/Duty/${id}`)
            return response.body as void;
        });
    }    
    public async ImportDefaultDuties( body:DutyImportDefaultsRequest ):Promise<Array<Duty>>{
        return this.tryWork(async () => {
            const response = await this.agent.post(`/Duty/import`)
                .send(body)
            return response.body as Array<Duty>;
        });
    }    
    public async GetSheriffDuties():Promise<Array<SheriffDuty>>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/SheriffDuty`)
            return response.body as Array<SheriffDuty>;
        });
    }    
    public async CreateSheriffDuty( model:SheriffDuty ):Promise<SheriffDuty>{
        return this.tryWork(async () => {
            const response = await this.agent.post(`/SheriffDuty`)
                .send(model)
            return response.body as SheriffDuty;
        });
    }    
    public async GetSheriffDutyById( id:string ):Promise<SheriffDuty>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/SheriffDuty/${id}`)
            return response.body as SheriffDuty;
        });
    }    
    public async UpdateSheriffDuty( id:string , model:SheriffDuty ):Promise<SheriffDuty>{
        return this.tryWork(async () => {
            const response = await this.agent.put(`/SheriffDuty/${id}`)
                .send(model)
            return response.body as SheriffDuty;
        });
    }    
    public async DeleteSheriffDuty( id:string ):Promise<void>{
        return this.tryWork(async () => {
            const response = await this.agent.delete(`/SheriffDuty/${id}`)
            return response.body as void;
        });
    }    
    public async GetLeaves():Promise<Array<Leave>>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/leaves`)
            return response.body as Array<Leave>;
        });
    }    
    public async CreateLeave( model:Leave ):Promise<Leave>{
        return this.tryWork(async () => {
            const response = await this.agent.post(`/leaves`)
                .send(model)
            return response.body as Leave;
        });
    }    
    public async GetLeaveById( id:string ):Promise<Leave>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/leaves/${id}`)
            return response.body as Leave;
        });
    }    
    public async UpdateLeave( id:string , model:Leave ):Promise<Leave>{
        return this.tryWork(async () => {
            const response = await this.agent.put(`/leaves/${id}`)
                .send(model)
            return response.body as Leave;
        });
    }    
    public async DeleteLeave( id:string ):Promise<void>{
        return this.tryWork(async () => {
            const response = await this.agent.delete(`/leaves/${id}`)
            return response.body as void;
        });
    }    
    public async GetLeaveCancelReasonCodes():Promise<Array<LeaveCancelReasonCode>>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/codes/leave-cancel`)
            return response.body as Array<LeaveCancelReasonCode>;
        });
    }    
    public async GetLeaveTypes():Promise<Array<LeaveCode>>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/codes/leave-type`)
            return response.body as Array<LeaveCode>;
        });
    }    
    public async GetLeaveSubCodes():Promise<Array<LeaveSubCode>>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/codes/leave-sub-type`)
            return response.body as Array<LeaveSubCode>;
        });
    }    
    public async GetCourtRoleCodes():Promise<Array<CourtRoleCode>>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/codes/courtroles`)
            return response.body as Array<CourtRoleCode>;
        });
    }    
    public async GetGenderCodes():Promise<Array<GenderCode>>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/codes/gender`)
            return response.body as Array<GenderCode>;
        });
    }    
    public async GetToken():Promise<void>{
        return this.tryWork(async () => {
            const response = await this.agent.get(`/token`)
            return response.body as void;
        });
    }    
}